//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMS_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OData_RTMSEntities : DbContext
    {
        public OData_RTMSEntities()
            : base("name=OData_RTMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SensorCode> SensorCodes { get; set; }
        public virtual DbSet<TempReading> TempReadings { get; set; }
        public virtual DbSet<WifiActivity> WifiActivities { get; set; }
    }
}
