//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMS_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorCode
    {
        public double id { get; set; }
        public Nullable<double> code { get; set; }
        public Nullable<System.DateTime> occurred { get; set; }
        public string notes { get; set; }
    }
}
