//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMS_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempReading
    {
        public int id { get; set; }
        public string node { get; set; }
        public Nullable<double> tempValue { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
    }
}
