//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTMS_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class WifiActivity
    {
        public double id { get; set; }
        public string mac { get; set; }
        public Nullable<double> connect { get; set; }
        public Nullable<System.DateTime> eventTime { get; set; }
        public string ap { get; set; }
    }
}
