//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 17/04/2018 17:54:08
namespace RTMS_API
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for SensorCodes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SensorCode> SensorCodes
        {
            get
            {
                if ((this._SensorCodes == null))
                {
                    this._SensorCodes = base.CreateQuery<SensorCode>("SensorCodes");
                }
                return this._SensorCodes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SensorCode> _SensorCodes;
        /// <summary>
        /// There are no comments for TempReadings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TempReading> TempReadings
        {
            get
            {
                if ((this._TempReadings == null))
                {
                    this._TempReadings = base.CreateQuery<TempReading>("TempReadings");
                }
                return this._TempReadings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TempReading> _TempReadings;
        /// <summary>
        /// There are no comments for WifiActivities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<WifiActivity> WifiActivities
        {
            get
            {
                if ((this._WifiActivities == null))
                {
                    this._WifiActivities = base.CreateQuery<WifiActivity>("WifiActivities");
                }
                return this._WifiActivities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<WifiActivity> _WifiActivities;
        /// <summary>
        /// There are no comments for SensorCodes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSensorCodes(SensorCode sensorCode)
        {
            base.AddObject("SensorCodes", sensorCode);
        }
        /// <summary>
        /// There are no comments for TempReadings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTempReadings(TempReading tempReading)
        {
            base.AddObject("TempReadings", tempReading);
        }
        /// <summary>
        /// There are no comments for WifiActivities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToWifiActivities(WifiActivity wifiActivity)
        {
            base.AddObject("WifiActivities", wifiActivity);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"RTMS_API\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><Entit" +
                "yType Name=\"SensorCode\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" " +
                "Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"code\" Type=\"Edm.Int32\" /><Pr" +
                "operty Name=\"occurred\" Type=\"Edm.DateTime\" /><Property Name=\"notes\" Type=\"Edm.St" +
                "ring\" /></EntityType><EntityType Name=\"TempReading\"><Key><PropertyRef Name=\"id\" " +
                "/></Key><Property Name=\"id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"" +
                "node\" Type=\"Edm.String\" /><Property Name=\"tempValue\" Type=\"Edm.Double\" /><Proper" +
                "ty Name=\"dateAdded\" Type=\"Edm.DateTime\" /></EntityType><EntityType Name=\"WifiAct" +
                "ivity\"><Key><PropertyRef Name=\"id\" /></Key><Property Name=\"id\" Type=\"Edm.Int32\" " +
                "Nullable=\"false\" /><Property Name=\"mac\" Type=\"Edm.String\" /><Property Name=\"conn" +
                "ect\" Type=\"Edm.Double\" /><Property Name=\"eventTime\" Type=\"Edm.DateTime\" /><Prope" +
                "rty Name=\"ap\" Type=\"Edm.String\" /></EntityType></Schema><Schema Namespace=\"Defau" +
                "lt\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"" +
                "Container\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"SensorCodes\" Entit" +
                "yType=\"RTMS_API.SensorCode\" /><EntitySet Name=\"TempReadings\" EntityType=\"RTMS_AP" +
                "I.TempReading\" /><EntitySet Name=\"WifiActivities\" EntityType=\"RTMS_API.WifiActiv" +
                "ity\" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for RTMS_API.SensorCode in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SensorCodes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class SensorCode : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SensorCode object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SensorCode CreateSensorCode(int ID)
        {
            SensorCode sensorCode = new SensorCode();
            sensorCode.id = ID;
            return sensorCode;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> code
        {
            get
            {
                return this._code;
            }
            set
            {
                this.OncodeChanging(value);
                this._code = value;
                this.OncodeChanged();
                this.OnPropertyChanged("code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _code;
        partial void OncodeChanging(global::System.Nullable<int> value);
        partial void OncodeChanged();
        /// <summary>
        /// There are no comments for Property occurred in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> occurred
        {
            get
            {
                return this._occurred;
            }
            set
            {
                this.OnoccurredChanging(value);
                this._occurred = value;
                this.OnoccurredChanged();
                this.OnPropertyChanged("occurred");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _occurred;
        partial void OnoccurredChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnoccurredChanged();
        /// <summary>
        /// There are no comments for Property notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string notes
        {
            get
            {
                return this._notes;
            }
            set
            {
                this.OnnotesChanging(value);
                this._notes = value;
                this.OnnotesChanged();
                this.OnPropertyChanged("notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _notes;
        partial void OnnotesChanging(string value);
        partial void OnnotesChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RTMS_API.TempReading in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TempReadings")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class TempReading : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TempReading object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TempReading CreateTempReading(int ID)
        {
            TempReading tempReading = new TempReading();
            tempReading.id = ID;
            return tempReading;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property node in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string node
        {
            get
            {
                return this._node;
            }
            set
            {
                this.OnnodeChanging(value);
                this._node = value;
                this.OnnodeChanged();
                this.OnPropertyChanged("node");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _node;
        partial void OnnodeChanging(string value);
        partial void OnnodeChanged();
        /// <summary>
        /// There are no comments for Property tempValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> tempValue
        {
            get
            {
                return this._tempValue;
            }
            set
            {
                this.OntempValueChanging(value);
                this._tempValue = value;
                this.OntempValueChanged();
                this.OnPropertyChanged("tempValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _tempValue;
        partial void OntempValueChanging(global::System.Nullable<double> value);
        partial void OntempValueChanged();
        /// <summary>
        /// There are no comments for Property dateAdded in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> dateAdded
        {
            get
            {
                return this._dateAdded;
            }
            set
            {
                this.OndateAddedChanging(value);
                this._dateAdded = value;
                this.OndateAddedChanged();
                this.OnPropertyChanged("dateAdded");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _dateAdded;
        partial void OndateAddedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateAddedChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RTMS_API.WifiActivity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("WifiActivities")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class WifiActivity : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new WifiActivity object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static WifiActivity CreateWifiActivity(int ID)
        {
            WifiActivity wifiActivity = new WifiActivity();
            wifiActivity.id = ID;
            return wifiActivity;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property mac in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string mac
        {
            get
            {
                return this._mac;
            }
            set
            {
                this.OnmacChanging(value);
                this._mac = value;
                this.OnmacChanged();
                this.OnPropertyChanged("mac");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _mac;
        partial void OnmacChanging(string value);
        partial void OnmacChanged();
        /// <summary>
        /// There are no comments for Property connect in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> connect
        {
            get
            {
                return this._connect;
            }
            set
            {
                this.OnconnectChanging(value);
                this._connect = value;
                this.OnconnectChanged();
                this.OnPropertyChanged("connect");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _connect;
        partial void OnconnectChanging(global::System.Nullable<double> value);
        partial void OnconnectChanged();
        /// <summary>
        /// There are no comments for Property eventTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> eventTime
        {
            get
            {
                return this._eventTime;
            }
            set
            {
                this.OneventTimeChanging(value);
                this._eventTime = value;
                this.OneventTimeChanged();
                this.OnPropertyChanged("eventTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _eventTime;
        partial void OneventTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OneventTimeChanged();
        /// <summary>
        /// There are no comments for Property ap in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ap
        {
            get
            {
                return this._ap;
            }
            set
            {
                this.OnapChanging(value);
                this._ap = value;
                this.OnapChanged();
                this.OnPropertyChanged("ap");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ap;
        partial void OnapChanging(string value);
        partial void OnapChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
